openapi: 3.0.2

info: 
  title: Portfolio server
  description: Marat Bakasov's server API to use for the website
  version: 1.0.0
  contact:
    name: Marat Bakasov
    email: bakasovmaratt04@gmail.com

paths:
  /guests:
    post:
      summary: Create a new guest
      requestBody: 
        required: true
        content:
          applicaion/json:
            schema: 
              $ref: '#/components/schemas/GuestRequest'
      responses:
        '201':
          description: Guest created successfully

  /guests/{guestId}:
    parameters: 
      - name: guestId
        required: true
        in: path
        schema:
          type: integer
    get:
      summary: Get guest data
      responses:
        '200':
          description: Guest data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GuestResponse'
        '404': 
          description: Guest not found
    patch:
      summary: Edit the guest data
      security: 
        - GuestBearer: []
      responses:
        '200':
          description: Guest updated succeffully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Reason for unauthorized access
        '404': 
          description: Guest not found

  /guests/{guestId}/stats:
    parameters: 
      - name: guestId
        required: true
        in: path
        schema:
          type: integer
    get:
      summary: Get guest stats
      security: 
        - GuestBearer: []
      responses:
        '200':
          description: Guest data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GuestStatsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Reason for unauthorized access
        '404': 
          description: Guest not found

  /stats:
    get:
      summary: Gets the app's general statistics
      responses:
        '200':
          description: Stats for the authorized user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Reason for unauthorized access


  /authorize:
    post:
      summary: Authorize and (if seccessful) get a JWT
      requestBody:
        required: true
        content:
          applicaion/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'

      responses:
        '200':
          description: Successful Authorization
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authenticated user
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Reason for unauthorized access

        
components:
  schemas:
    AuthRequest: 
      type: object
      required: 
        - id
        - password
      properties:
        id:
          type: integer
        password:
          type: string

    GuestResponse:
      type: object
      required: 
        - id
        - name
      properties:
        id: 
          type: integer
        name: 
          type: string

    GuestRequest:
      type: object
      required: 
        - name
        - secret
      properties:
        name: 
          type: string
        secret: 
          type: string

    GuestStatsResponse:
      type: object
      required:
        - guestId
        - visits
      properties:
        guestId:
          type: string
        visits:
          type: array
          items:
            $ref: '#/components/schemas/GuestStats'
    GuestStats:
      type: object
      required: 
        - date
        - drawings
        - linesDrawn
      properties:
        date: 
          type: string
          format: date-time
        drawings:
          type: integer
        linesDrawn:
          type: integer
    StatsResponse:
      type: object
      required: 
        - totalGuests
        - totalLinesDrawn
        - guests
      properties:
        totalGuests:
          type: integer
        totalLinesDrawn:
          type: integer
        guests:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/GuestResponse'
  securitySchemes:
    GuestBearer:
      type: http
      scheme: bearer
