// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	GuestBearerScopes = "GuestBearer.Scopes"
)

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	GuestName string `json:"guestName"`
	Password  string `json:"password"`
}

// GuestRequest defines model for GuestRequest.
type GuestRequest struct {
	Name   string `json:"name"`
	Secret string `json:"secret"`
}

// GuestResponse defines model for GuestResponse.
type GuestResponse struct {
	Id     int    `json:"id"`
	Name   string `json:"name"`
	Secret string `json:"secret"`
}

// GuestStats defines model for GuestStats.
type GuestStats struct {
	Date       time.Time `json:"date"`
	Drawings   int       `json:"drawings"`
	LinesDrawn int       `json:"linesDrawn"`
}

// GuestStatsResponse defines model for GuestStatsResponse.
type GuestStatsResponse struct {
	GuestId string       `json:"guestId"`
	Visits  []GuestStats `json:"visits"`
}

// StatsResponse defines model for StatsResponse.
type StatsResponse struct {
	Guests          []GuestResponse `json:"guests"`
	TotalGuests     int             `json:"totalGuests"`
	TotalLinesDrawn int             `json:"totalLinesDrawn"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authorize and (if seccessful) get a JWT
	// (POST /authorize)
	PostAuthorize(c *gin.Context)
	// Create a new guest
	// (POST /guests)
	PostGuests(c *gin.Context)
	// Get guest data
	// (GET /guests/{guestId})
	GetGuestsGuestId(c *gin.Context, guestId int)
	// Edit the guest data
	// (PATCH /guests/{guestId})
	PatchGuestsGuestId(c *gin.Context, guestId int)
	// Get guest stats
	// (GET /guests/{guestId}/stats)
	GetGuestsGuestIdStats(c *gin.Context, guestId int)
	// Gets the app's general statistics
	// (GET /stats)
	GetStats(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuthorize operation middleware
func (siw *ServerInterfaceWrapper) PostAuthorize(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthorize(c)
}

// PostGuests operation middleware
func (siw *ServerInterfaceWrapper) PostGuests(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostGuests(c)
}

// GetGuestsGuestId operation middleware
func (siw *ServerInterfaceWrapper) GetGuestsGuestId(c *gin.Context) {

	var err error

	// ------------- Path parameter "guestId" -------------
	var guestId int

	err = runtime.BindStyledParameter("simple", false, "guestId", c.Param("guestId"), &guestId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter guestId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGuestsGuestId(c, guestId)
}

// PatchGuestsGuestId operation middleware
func (siw *ServerInterfaceWrapper) PatchGuestsGuestId(c *gin.Context) {

	var err error

	// ------------- Path parameter "guestId" -------------
	var guestId int

	err = runtime.BindStyledParameter("simple", false, "guestId", c.Param("guestId"), &guestId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter guestId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(GuestBearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchGuestsGuestId(c, guestId)
}

// GetGuestsGuestIdStats operation middleware
func (siw *ServerInterfaceWrapper) GetGuestsGuestIdStats(c *gin.Context) {

	var err error

	// ------------- Path parameter "guestId" -------------
	var guestId int

	err = runtime.BindStyledParameter("simple", false, "guestId", c.Param("guestId"), &guestId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter guestId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(GuestBearerScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGuestsGuestIdStats(c, guestId)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStats(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/authorize", wrapper.PostAuthorize)
	router.POST(options.BaseURL+"/guests", wrapper.PostGuests)
	router.GET(options.BaseURL+"/guests/:guestId", wrapper.GetGuestsGuestId)
	router.PATCH(options.BaseURL+"/guests/:guestId", wrapper.PatchGuestsGuestId)
	router.GET(options.BaseURL+"/guests/:guestId/stats", wrapper.GetGuestsGuestIdStats)
	router.GET(options.BaseURL+"/stats", wrapper.GetStats)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWwW7jNhD9FYItsC3g2s42J52abQsji7YINlvsIchhIo1k7kqkdjiK4Qb+94JDWZYj",
	"OXEa+NCiN4nkDN+89zjkg05dVTuLlr1OHrRPl1iBfF40vPyAXxv0HH5rcjUSG5TJIgz/ARWGH17XqBPt",
	"mYwt9Gaia/B+5SgbmdxMNOHXxhBmOrnp5elF3U62Ue7uM6YcUi7CwoNw7CEkHlNCfh6HjRDa5U8A8LWz",
	"HocITL9YYxkLpBD2amQm05Nj4V0zRBn3sWXAgiF3VAHrRAZ+YCM5B8AygpWxhR+vpzQW/S8EKzs2/wi7",
	"bNzLuBf+dBWHmRbLXGajpN4bbyIDhrGSj28Jc53ob2Y7o89al896pG06NEAE63GjXgYt2j3G4B+D/IXo",
	"umwDgBPNjqFcdEmHYsmC316iWD/lMH6yLWFYfHR0Q4bX1wF/rFgyvUMgpK67hKi7ONRlWTLXehOSGJu7",
	"sDR1liGV84EVmDIEwRfw7r4CAub5+U9FGJ+mrtoekET/HubUu7hQzIw+JVOzcfbx9BuvPNI9krq4ulTs",
	"VONR5Y4UL1Gt8M4bMS8bLkPqK0ecu9K4Nio4AcnHxGfT+XQe9nM1WqiNTvSP0/n0rXQ1XgoXM2h46cj8",
	"FZ3hYh8L/oAALzhaXznPF92yKE1g0GXrLSloJQ7qujQpGGdnn72zu979nKv6bX2zLz9TgzIQLSeo387n",
	"4zvz+Nb7jmf3BWXBvg7vP31UMiV8B17QcsiJWVCBhm1pMzTcQN3rJk3R+7wp1ZZDQRl0OZ+fvaIMJHI0",
	"LOMDgnexhsZ26mYKBMc/K+LPXqJ4qpqqAlrrRHfGUGAz9Z3Jlcdtxd+rAlmBev/po0TNdr3msNO6c34C",
	"m+3d10f57GxIsCRRKaE4w3f6lutH1PwsSxQoiytVtHt2LMwe2u69kS6MI3QssGVj0fX5Vx2DF/T1oQdi",
	"2RkwROueH2LGOla5a+xjpyyQIwtdkhoIKmQkr5ObB21CjtCZdq2z6BXeF2rSq2pwedxKf0uXI/4Kw8dQ",
	"OlZXU2c7xfNW8H/tIX6JhO0VKiLtXZ43t4HsncS/ZoblpurrPGb5md8+Co8yfnwNndr9+w+lI47A/8IP",
	"z7bfPlxPdbiDnZ51z8kN86xXZEH3cuspKU+J/8jlv0D2sb66fuNVgRYJSvGA8WxSH/Jt/g4AAP//OwfG",
	"dM8PAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
