// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for Role.
const (
	Admin Role = "admin"
	User  Role = "user"
)

// CreateRoomRequest defines model for CreateRoomRequest.
type CreateRoomRequest struct {
	IsPrivate bool   `json:"isPrivate"`
	Name      string `json:"name"`

	// Password the password a user needs to provide when entering a private room
	Password *string `json:"password,omitempty"`
}

// JoinRoomRequest defines model for JoinRoomRequest.
type JoinRoomRequest struct {
	Password *string `json:"password,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

// Role defines model for Role.
type Role string

// RoomResponse defines model for RoomResponse.
type RoomResponse struct {
	Id          int    `json:"id"`
	IsPrivate   bool   `json:"isPrivate"`
	MemberCount int    `json:"memberCount"`
	Name        string `json:"name"`
}

// UserRequest defines model for UserRequest.
type UserRequest struct {
	Name       string              `json:"name"`
	ProfilePic *openapi_types.File `json:"profilePic,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Created openapi_types.Date `json:"created"`
	Id      int                `json:"id"`
	Name    string             `json:"name"`

	// ProfilePic base 64 encoded png image
	ProfilePic openapi_types.File `json:"profilePic"`
}

// UserToken defines model for UserToken.
type UserToken struct {
	Role   *Role   `json:"role,omitempty"`
	UserId *string `json:"userId,omitempty"`
}

// GetRoomsParams defines parameters for GetRooms.
type GetRoomsParams struct {
	// Page The page number to retrieve (optional)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize The number of items per page (optional)
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequest

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody = RegisterRequest

// PostRoomsJSONRequestBody defines body for PostRooms for application/json ContentType.
type PostRoomsJSONRequestBody = CreateRoomRequest

// PostRoomsRoomIdJSONRequestBody defines body for PostRoomsRoomId for application/json ContentType.
type PostRoomsRoomIdJSONRequestBody = JoinRoomRequest

// PutUsersUserIdJSONRequestBody defines body for PutUsersUserId for application/json ContentType.
type PutUsersUserIdJSONRequestBody = UserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login
	// (POST /login)
	PostLogin(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /register)
	PostRegister(w http.ResponseWriter, r *http.Request)
	// Retrieve general info about rooms
	// (GET /rooms)
	GetRooms(w http.ResponseWriter, r *http.Request, params GetRoomsParams)
	// Create a new chat room
	// (POST /rooms)
	PostRooms(w http.ResponseWriter, r *http.Request)
	// Information about a room
	// (GET /rooms/{roomId})
	GetRoomsRoomId(w http.ResponseWriter, r *http.Request, roomId string)
	// Join a chat room
	// (POST /rooms/{roomId})
	PostRoomsRoomId(w http.ResponseWriter, r *http.Request, roomId string)
	// Delete a user
	// (DELETE /users/{userId})
	DeleteUsersUserId(w http.ResponseWriter, r *http.Request, userId string)
	// Get user data
	// (GET /users/{userId})
	GetUsersUserId(w http.ResponseWriter, r *http.Request, userId string)
	// Update user data
	// (PUT /users/{userId})
	PutUsersUserId(w http.ResponseWriter, r *http.Request, userId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login
// (POST /login)
func (_ Unimplemented) PostLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new user
// (POST /register)
func (_ Unimplemented) PostRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve general info about rooms
// (GET /rooms)
func (_ Unimplemented) GetRooms(w http.ResponseWriter, r *http.Request, params GetRoomsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new chat room
// (POST /rooms)
func (_ Unimplemented) PostRooms(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Information about a room
// (GET /rooms/{roomId})
func (_ Unimplemented) GetRoomsRoomId(w http.ResponseWriter, r *http.Request, roomId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Join a chat room
// (POST /rooms/{roomId})
func (_ Unimplemented) PostRoomsRoomId(w http.ResponseWriter, r *http.Request, roomId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a user
// (DELETE /users/{userId})
func (_ Unimplemented) DeleteUsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user data
// (GET /users/{userId})
func (_ Unimplemented) GetUsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update user data
// (PUT /users/{userId})
func (_ Unimplemented) PutUsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostRegister operation middleware
func (siw *ServerInterfaceWrapper) PostRegister(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRooms operation middleware
func (siw *ServerInterfaceWrapper) GetRooms(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRoomsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRooms(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostRooms operation middleware
func (siw *ServerInterfaceWrapper) PostRooms(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRooms(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRoomsRoomId operation middleware
func (siw *ServerInterfaceWrapper) GetRoomsRoomId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", chi.URLParam(r, "roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomsRoomId(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostRoomsRoomId operation middleware
func (siw *ServerInterfaceWrapper) PostRoomsRoomId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", chi.URLParam(r, "roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRoomsRoomId(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersUserId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"admin"})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUsersUserId(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersUserId(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutUsersUserId(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/login", wrapper.PostLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/register", wrapper.PostRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rooms", wrapper.GetRooms)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rooms", wrapper.PostRooms)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rooms/{roomId}", wrapper.GetRoomsRoomId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rooms/{roomId}", wrapper.PostRoomsRoomId)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{userId}", wrapper.DeleteUsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{userId}", wrapper.GetUsersUserId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{userId}", wrapper.PutUsersUserId)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYwXLbNhD9FQzaQzvDseTU7UE3x51mnPFB49jTg8cHiFxRSEgsDYB2FA//vbML0hQp",
	"UVQc2+nJlghwF+/te7vQo4wxL9CA8U7OHqWLV5Ar/vfMgvJwiZhfwl0JztOXhcUCrNfAS7SbW32vPNAH",
	"vy5AzuQCMQNlZBVJo/LNJ85bbVJ6UCjnHtAm9DABF1tdeI1GzqRfgWieCiVKB1YYgMQJj6KweK8TEA8r",
	"MAKMB3qfUKIISQiLmMuoH66KpIW7UltI5OxmI+c6wdunHbj4DLGnBD+iNntPvnmC/fEGY1xgqs1ggIOw",
	"OyDyxoZdSVxCqp0H+9PzwIzDgClz2qOSXBsZSSqAjQ1t+MCOK9A42FGYm2lp4yEFS7tGCjaHfAH2DEvj",
	"d+8fQKNfYonsvitqMGjj7wLh2j2LCItLncFcx/R4iTZXno6ljbLrUTkMlmdIZgjgmM0h6URMgqi2Ehwi",
	"48ATdQ1ioRyIv04EmBgTSERhUqFzlVLk7z0781Qz0xyoE30Ilyv8AmYbFFsX8a8WlnImf5m03jqpjXXC",
	"hV6Fwj4fEE8vZhVJB3FptV9/oreEYAtQFuxp6Vftp38aAD7+eyWjYOZc4vy0xWPlfSErerE2S9wG+XR+",
	"LpZog/1atgir6FkkVOlXYLyOm88mEfFKeTZfkSujUsjB+COKpj0BwpDxwjNaSMoVp/NzGcl7sC5EPD6a",
	"Hk0JFyzAqELLmfyDvyLf8Cs+8SQjx2TYMSiEwOc8CEk5R+fZVGWgGZx/j8mayxWNhyBqVRRZnf3ks0PT",
	"dr0x6jqGXXWLydsS+IsgGM733XT6YrHbquPAXbo4MeHKOAbnlmVGOJ5Mj7d5vTZEH1r9DRKBVjCgYql0",
	"BkmnzuTs5rG6jaQr85yUVMfgNRNb94z9TDSd5ZXI6Deug/jYBUlb4mAh2UAxIwNZgUrA8vYLDIluv+NC",
	"my80n9DwYuAhW4vaTVhAjRDVLrFXTNV0+53vVSJq3ESjRJVZUMlawFftvBshrAFIKMopZBLoQ8z5QCns",
	"oO4D+EteQMKzKgfPx7/p53fFg1oKwpTU5+j4FrzVcA/iN+RVKvudWh6tviuB/ThYviyCX7ewJLBUZebl",
	"7DiSuTY6pyngONpqGlW0K486BVwK7SF3ogAbcjsokU/620Ay76aRzNXXkM2f05HUbn9Q/pz7ePvYGHva",
	"VqGsVetd1jBXqTZcikz7E0e9Qh8rpZrYFAxYlQnqGkItsAy277hpDztBXU+vYQPbl5TnGsHZUxNrxPuy",
	"VlBfTp5hBdwwqWB7BkC+QN5dWhDahEC0o09mZ1S4ue1yGwCsTeKpkW84xeSR/pwn1ahlXPK6beNg4VEX",
	"b3Vnm6VdovbBc/uK3bWrqm0VtbXB8xITdTJEFHqxxNKMNdRzE8ZVjaaWkqqhH9XSGwD98krtX6kP0Onx",
	"gE5NSvf+wqLHGDMn9wonQXBMCouGNKNNjNZC7J9+afg+ydBJhOqLhRqsmzyGub4KyWQQbppdHv/m72nw",
	"cNfhFnAIk2Wz9Icls2MACqn2m8IBU+SgFsJrO9iPoFzf+XtgB7Dqn4Io2pAF/Tw8X2zA32dBAU/l1WAL",
	"f1u2ejR9AB9mVEqRLazc5WDlm9H08ga2+evM4be/IRbLIlH+/8XhNae0SePo9uq/AAAA//8t3jNwQBYA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
